### ISSUE TITLE
Client crash when join a server

### ISSUE THREAD

**Issue by frank89722** [CorgiTaco/Better-Weather#16]
Better weather 1.1.4

crash report: https://pastebin.com/37Rtr28S

**Comment by googhigg** [comment]
Had the same issue. At the moment I'm trying to fix it but no promises.

crash report: https://pastebin.com/dcyqAacp

**Comment by kreezxil** [comment]
confirmed same issue here:
https://gist.github.com/59dfb3dda2963eecf012e8f5847449c4 crash occurs on the client with npe name is null. CAUSED by the 1.1.4 update.

It should be noted that I am using 1.16.4-35.1.13 due heavily that JEI breaks on any version after it.

**Comment by googhigg** [comment]
I found a temporary fix

Before connecting to the server, load a single player world with the mod.
Joining in the server after that causes no problems.
This must be done every time you start a new instance of Minecraft though.

**Comment by kreezxil** [comment]
the temporary fix is to roll back before this last update

**Comment by CorgiTaco** [comment]
My bad peeps, I forgot that clients dont carry the same data as servers so my apologies. But it should be fixed now! https://www.curseforge.com/minecraft/mc-mods/better-weather/files/3163484

**Comment by CorgiTaco** [comment]
@frank89722 @kreezxil @googhigg @mindy15963 I forgot to add colors in that version i posted b4 this: https://www.curseforge.com/minecraft/mc-mods/better-weather/files/3163510

**Comment by kreezxil** [comment]
thanks corgi!

**Comment by LegoLoverGo** [comment]
[crash-2021-03-14_18.30.27-client.txt](https://github.com/CorgiTaco/Better-Weather/files/6137758/crash-2021-03-14_18.30.27-client.txt)
This still persists
